const router = require('express').Router();
const verifyJwt = require('../middleware/verifyJwt');
const requireCurrentHrRole = require('../middleware/requireCurrentHrRole');
const requireRole = require('../middleware/requireRole');
const validateRequest = require('../middleware/validateRequest');
const schema = require('../validation/hrAttendance.schema');
const controller = require('../controllers/hrAttendance.controller');
router.use(verifyJwt,requireCurrentHrRole(['admin','factory_manager','ho']));
router.get('/review-queue',requireRole(['admin','ho']),validateRequest(schema.reviewQueue),controller.reviewQueue);
router.get('/fm-summary',requireRole(['admin','factory_manager']),validateRequest(schema.fmSummary),controller.fmSummary);
router.get('/sheets/:sheetId/review-detail',requireRole(['admin','ho']),validateRequest(schema.detail),controller.reviewDetail);
router.post('/sheets/:sheetId/leaves/:leaveId/decision',requireRole(['admin','ho']),validateRequest(schema.decideLeave),controller.decideLeave);
router.post('/sheets/:sheetId/return',requireRole(['admin','ho']),validateRequest(schema.returnSheet),controller.returnSheet);
router.post('/sheets/:sheetId/review',requireRole(['admin','ho']),validateRequest(schema.reviewSheet),controller.reviewSheet);
router.get('/roster',validateRequest(schema.selection),controller.roster);
router.get('/sheet',validateRequest(schema.selection),controller.load);
router.get('/sheets/:sheetId',validateRequest(schema.detail),controller.get);
router.get('/sheets/:sheetId/history',validateRequest(schema.history),controller.history);
router.post('/sheets',requireRole(['admin','factory_manager']),validateRequest(schema.populate),controller.populate);
router.put('/sheets/:sheetId/rows',requireRole(['admin','factory_manager']),validateRequest(schema.save),controller.save);
router.post('/sheets/:sheetId/leave',requireRole(['admin','factory_manager']),validateRequest(schema.leave),controller.leave);
router.post('/sheets/:sheetId/submit',requireRole(['admin','factory_manager']),validateRequest(schema.submit),controller.submit);
module.exports = router;
