import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import authApi from '../api/authApi';
import { Button, Table, TableHeader, TableBody, TableRow, TableCell, Badge } from '../components/ui';
const SubcontractEstimates = () => {
  const navigate = useNavigate(); const [data, setData] = useState({ estimates: [], pagination: {} }); const [error, setError] = useState(''); const [page, setPage] = useState(1);
  useEffect(() => { authApi.get('/subcontract-estimates', { params: { page, limit: 20 } }).then(r => setData(r.data)).catch(e => setError(e.response?.data?.message || 'Failed to load subcontract estimates.')); }, [page]);
  return <div className="space-y-6"><div className="flex items-center justify-between border-b border-white/5 pb-5"><div><span className="text-[10px] uppercase tracking-widest text-amber-500">Projects Module</span><h1 className="text-3xl font-extrabold text-slate-100">Subcontract Estimates</h1><p className="text-xs text-slate-400 mt-1">Create and maintain Work Order-specific subcontract scope.</p></div><Button onClick={() => navigate('/subcontract-estimates/new')}>+ New Estimate</Button></div>{error && <div className="rounded-xl border border-rose-500/20 bg-rose-500/10 p-3 text-sm text-rose-300">{error}</div>}<Table containerClassName="min-w-[760px]"><TableHeader><TableRow hover={false}><TableCell isHeader>Work Order</TableCell><TableCell isHeader>Status</TableCell><TableCell isHeader>Revision</TableCell><TableCell isHeader>Total</TableCell><TableCell isHeader>Updated</TableCell><TableCell isHeader>Action</TableCell></TableRow></TableHeader><TableBody>{data.estimates.map(e => <TableRow key={e.subcontract_estimate_id}><TableCell className="font-mono text-slate-200">{e.work_order_no}</TableCell><TableCell><Badge variant={e.estimate_status === 'Draft' ? 'slate' : 'sky'}>{e.estimate_status}</Badge></TableCell><TableCell>{e.estimate_revision}</TableCell><TableCell>₹{Number(e.estimate_amount || 0).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</TableCell><TableCell>{e.updated_at ? new Date(e.updated_at).toLocaleDateString('en-IN') : '—'}</TableCell><TableCell><Button size="sm" variant="secondary" onClick={() => navigate(e.estimate_status === 'Draft' ? `/subcontract-estimates/${e.subcontract_estimate_id}/edit` : `/subcontract-estimates/${e.subcontract_estimate_id}`)}>Open</Button></TableCell></TableRow>)}{!data.estimates.length && <TableRow><TableCell colSpan={6}>No subcontract estimates found.</TableCell></TableRow>}</TableBody></Table><div className="flex justify-between text-xs text-slate-400"><span>Page {page} of {data.pagination.totalPages || 1}</span><div className="flex gap-2"><Button size="sm" variant="ghost" disabled={page <= 1} onClick={() => setPage(p => p - 1)}>Previous</Button><Button size="sm" variant="ghost" disabled={page >= (data.pagination.totalPages || 1)} onClick={() => setPage(p => p + 1)}>Next</Button></div></div></div>;
};
export default SubcontractEstimates;
